#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SafeWordPearlHacks18.Resource", IsApplication=true)]

namespace SafeWordPearlHacks18
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::SafeWordPearlHacks18.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::SafeWordPearlHacks18.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int bMainMonitor = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int cbPhone1 = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int cbPhone2 = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int cbPhone3 = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int cbText1 = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int cbText2 = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int cbText3 = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int etOptionsDistressCommand1 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int etOptionsDistressNumber1 = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int etOptionsDistressNumber2 = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int etOptionsDistressNumber3 = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int space1 = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int space2 = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int tvOptionsDistress1 = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int tvOptionsDistress2 = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int tvOptionsDistress3 = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int tvOptionsDistressNumber1 = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int tvOptionsDistressPhone2 = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Options = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
